news/urls.py
from django.urls import path

from news.models import Giornalista
from .views import GiornalistaDetailViewCB, home, ArticoloDetailViewCB, ArticoloListView, GiornalistaListView

app_name="news"

urlpatterns = [
    path('', home, name="homeview"),
    #path('articoli/<int:pk>', articoloDetailView, name="articolo_detail")
    path('articoli/<int:pk>', ArticoloDetailViewCB.as_view(), name="articolo_detail"),
    path('lista_articoli/', ArticoloListView.as_view(), name="Lista_articoli"),
    path('giornalisti/<int:pk>', GiornalistaDetailViewCB.as_view(), name="giornalista_detail"),
    path('lista_giornalisti/', GiornalistaListView.as_view(), name="Lista_giornalisti"),
]

prima_app/urls.py
from django.urls import path
from prima_app. views import homepage
from prima_app.views import welocome
from prima_app.views import lista
from prima_app.views import chi_siamo
from prima_app.views import variabili
from prima_app.views import index

app_name="prima_app"
urlpatterns=[
path('homepage', homepage, name='homepage'),
path('welcome', welocome, name='welcome'),
path('lista', lista, name='lista'),
path('chi_siamo', chi_siamo, name='chi_siamo'),
path('variabili', variabili, name='variabili'),
path('', index, name='index'),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("prima_app.urls",namespace="prima_app")),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('news/',include("news.urls",namespace="news")),
    path('prova_pratica_1/',include("prova_pratica_1.urls",namespace="Prova_pratica_1")),
]

prova_pratica_1/urls.py
from django.urls import path
from prova_pratica_1.views import view_b,view_c,view_e


app_name="prova_pratica_1"
urlpatterns=[
    path('view_b/', view_b, name='view_b'),
    path('view_c/', view_c, name='view_c'),
    path('view_e/', view_e, name='view_e'),
]

seconda_app/urls.py
from django.urls import path
from seconda_app.views import es_if
from seconda_app.views import if_else_elif
from seconda_app.views import es_for


app_name= 'seconda_app'
urlpatterns=[
path('es_if', es_if, name='es_if'),
path('if_else_elif', if_else_elif, name='if_else_elif'),
path('es_for', es_for, name='es_for'),
]

news/models.py
from django.db import models

class Giornalista(models.Model):
    """modello generico di un giornalista"""
    nome= models.CharField(max_length=20)
    cognome= models.CharField(max_length=20)

    #def __str__(self):
        #return self.nome + " " + self.cognome
    
    class Meta:
        verbose_name = "Giornalista"
        verbose_name_plural = "Giornalisti"
        
class Articolo(models.Model):
    """modello generico di un articolo news"""
    titolo= models.CharField(max_length=100)
    contenuto= models.TextField()
    giornalista= models.ForeignKey(Giornalista, on_delete=models.CASCADE, related_name="articoli")

    #def __str__(self):
        #return self.titolo

    class Meta:
        verbose_name = "Articolo"
        verbose_name_plural = "Articoli"

prova_pratica_1/models.py
from django.db import models

seconda_app/models.py
from django.db import models

# Create your models here.

news/views.py
from typing import Generic
from django.db import models
from django.http import HttpResponse, response
from django.shortcuts import render, get_object_or_404
from .models import Articolo, Giornalista
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

def home(request):
    articoli= Articolo.objects.all()
    giornalisti = Giornalista.objects.all()
    context ={"articoli": articoli, "giornalisti": giornalisti}
    print(context)
    return render(request, "homepage_news.html", context)

def articoloDetailView(request, pk):
    # articolo = Articolo.objects.get(pk=pk)
    articolo= get_object_or_404(Articolo, pk=pk)
    context= {"articolo": articolo}
    return render(request, "articolo_detail.html", context)

class ArticoloDetailViewCB(DetailView):
    model = Articolo
    template_name = "articolo_detail.html"

class ArticoloListView(ListView):
    model= Articolo
    template_name= "lista_articoli.html"

    def get_context_data(self, **kwargs):
        context =super().get_context_data(**kwargs)
        context["articoli"] = Articolo.objects.all()
        return context

class GiornalistaDetailViewCB(DetailView):
    model = Giornalista
    template_name = "giornalista_detail.html"

class GiornalistaListView(ListView):
    model= Giornalista
    template_name= "lista_giornalisti.html"

    def get_context_data(self, **kwargs):
        context =super().get_context_data(**kwargs)
        context["giornalisti"] = Giornalista.objects.all()
        return context

prima_app/views.py
from typing import ContextManager
from django.shortcuts import render

# Create your views here.
def homepage(request):
    return render(request, "homepage.html")

def welocome(request):
    return render(request, "welcome.html")

def lista(request):
    return render(request, "lista.html")

def chi_siamo(request):
    return render(request, "chi_siamo.html")

def variabili(request):
    context= {
        'var1': 'Prima Variabile',
        'var2': 'seconda Variabile',
        'var3': 'terza Variabile'
    }
    return render(request, "variabili.html",context)

def index(request):
    return render(request, "index.html")

prova_pratica_1/views.py
from urllib import response
from django.shortcuts import render
from django.http import JsonResponse

def view_b(request):
    context= {
        'materie': ["Matematica","Italiano","Inglese","Storia","Geografia"],
    }
    return render(request, "view_b.html",context)

def view_c(request):
    context= {
        'voti':{
            'Giuseppe Gullo':[("Matematica",9,0),("Italiano",7,3),("Inglese",7.5,4),("Storia",7.5,4),("Geografia",5,7)],
            'Antonio Barbera':[("Matematica",8,1),("Italiano",6,1),("Inglese",9.5,0),("Storia",8,2),("Geografia",8,1)],
            'Nicola Spina':[("Matematica",7.5,2),("Italiano",6,2),("Inglese",4,3),("Storia",8.5,2),("Geografia",8,2)]
        }
    }
    return render(request, "view_c.html",context)

def view_e(request):
    context= {
        'materie': ["Matematica","Italiano","Inglese","Storia","Geografia"],
    }
    response = JsonResponse(context)
    return response

seconda_app/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def es_if(request):
    context={
        'var1': 200,
        'var2': 200,
        'var3': 300,
    }
    return render(request, "es_if.html", context)

def if_else_elif(request):
    context={
        'var1': 100,
        'var2': 100.0,
        'var3': 150.50,
    }
    return render(request, "if_else_elif.html", context)

def es_for(request):
    context={
        'list1': [1, datetime.date(2019,7,16), 'Do not give up!'],
        'list2': [1, datetime.date(2019,7,16), 'Do not give up!'],
    }
    return render(request, "es_for.html", context)

news/templates/articolo_detail.html
{% extends 'base.html' %}

{% block title %} 
    {{articolo.titolo}}
{% endblock title %}

{% block content %}

    <h1>{{articolo.titolo}}</h1>
    <h3>{{articolo.contenuto}}</h3>
    <h5>Autore: {{articolo.giornalista}}</h5>
        
{% endblock content %}

news/templates/giornalista_detail.html
{% extends "base.html" %}

{% block title %} 
    Lista Giornalisti
{% endblock title %}

{% block content %}
    <h4>Giornalisti: </h4>
        {% for articolo in articoli %}
            <p><strong>Giornalista: </strong><a href="/news/giornalisti/{{ giornalista.nome}}">{{giornalista.cognome}}</a></p>
            <hr>
        {% endfor %}
    
{% endblock content %}

news/templates/homepage_news.html
{% extends "base.html" %}

{% block title %} 
    Articoli e Giornalisti
{% endblock title %}
{% block content %}
    <h4>Articoli: </h4>
        {% for articolo in articoli %}
            <p><strong>Titilo: </strong>{{ giornalista.nome}}</p>
            <p><strong>Contenuto: </strong>{{ articolo.contenuto}}</p>
            <p><strong>Autore: </strong>{{ articolo.giornalista}}</p>
            <hr>
        {% endfor %}
    <h4>Giornalisti: </h4>
        {% for giornalista in giornalisti %}
            <p><strong>Nome: </strong>{{ giornalista.nome}}</p>
            <p><strong>Cognome: </strong>{{ giornalista.cognome}}</p>
            <hr>
        {% endfor %}
{% endblock content %}

news/templates/lista_articoli.html
{% extends "base.html" %}

{% block title %} 
    Lista Articoli
{% endblock title %}

{% block content %}
    <h4>Articoli: </h4>
        {% for articolo in articoli %}
            <p><strong>Titilo: </strong><a href="/news/articoli/{{ articolo.id}}">{{articolo.titolo}}</a></p>
            <p><strong>Contenuto: </strong>{{ articolo.contenuto}}</p>
            <p><strong>Autore: </strong>{{ articolo.giornalista}}</p>
            <hr>
        {% endfor %}
    
{% endblock content %}

news/templates/lista_giornalisti.html
{% extends "base.html" %}

{% block title %} 
    Lista Giornalisti
{% endblock title %}

{% block content %}
    <h4>Giornalisti: </h4>
        {% for giornalista in giornalisti %}
            <p><strong>Nome: </strong><a href="/news/giornalisti/{{ giornalista.id}}">{{giornalista.nome}}</a></p>
            <p><strong>Cognome: </strong>{{ giornalista.cognome}}</p>
            <hr>
        {% endfor %}
    
{% endblock content %}

prima_app/templates/chi_siamo.html
{% extends "base.html" %}

{% block title %} {{block.super}} | Chi siamo {% endblock title %}

{% block content %}
    <h1>Chi siamo</h1>
    <p>lorem ipsum</p>
{% endblock content %}

prima_app/templates/homepage.html
{% extends "base.html" %}

{% block title %} {{block.super}} | Home page {% endblock title %}

{% block content %}
    <h1>Benvenuto</h1>
{% endblock content %}

prima_app/templates/index.html
{% extends "base.html" %}

{% block title %} {{block.super}} | Index {% endblock title %}

{% block content %}
    <ol>
        <h3>Link prima app:</h3>
        <li><a href="{% url 'prima_app:homepage'%}">Home page benvenuto</a></li>
        <li><a href="{% url 'prima_app:welcome'%}">Welcome</a></li>
        <li><a href="{% url 'prima_app:lista'%}">Lista</a></li>
        <li><a href="{% url 'prima_app:chi_siamo'%}">Chi siamo</a></li>
        <li><a href="{% url 'prima_app:variabili'%}">Variabili</a></li>
        <h3>Link seconda app:</h3>
        <li><a href="{% url 'seconda_app:es_for'%}">Es_for</a></li>
        <li><a href="{% url 'seconda_app:es_if'%}">Es_if</a></li>
        <li><a href="{% url 'seconda_app:if_else_elif'%}">If_else_elif</a></li>
    </ol>
{% endblock content %}

prima_app/templates/lista.html
{% extends "base.html" %}

{% block title %} {{block.super}} | Lista {% endblock title %}

{% block content %}
    <ol>
        <li>primo</li>
        <li>secondo</li>
        <li>terzo</li>
    </ol>
{% endblock content %}

prima_app/templates/variabili.html
{% extends "base.html" %}

{% block title %} {{block.super}} | Variabili {% endblock title %}

{% block content %}
    <ol>
        <li>{{var1}}</li>
        <li>{{var2}}</li>
        <li>{{var3}}</li>
    </ol>
{% endblock content %}

prima_app/templates/welcome.html
{% extends "base.html" %}

{% block title %} {{block.super}} | Welcome {% endblock title %}

{% block content %}
    <h1>Welcome</h1>
    <p>now in english</p>
    <h1>:)</h1>
{% endblock content %}

prova_pratica_1/templates/view_b.html
{% extends 'base.html'%}

{%block content%}
{% for x in materie %}
    <ul><li>{{x}}</li></ul>
{% endfor %}
    
{% endblock content %}

prova_pratica_1/templates/view_c.html
{%extends "base.html"%}

{%block title%} {{block.super}} | Amogus ඞ {%endblock title%}

{%block content%}
    <ul>
        {% for studente, valutazione in voti.items %}
            <li>{{ studente }}</li>
            <ul>
            {% for a in valutazione %}
                <li>
                    {% for i in a %}
                        {% if i != a|last %}
                        <span>{{ i }},</span>
                        {% else %}
                        <span>{{ i }}</span>
                        {% endif %}
                    {% endfor %}
                </li>
            {% endfor %}
            </ul>
        {% endfor %}
    </ul>
{%endblock content%}

seconda_app/templates/es_for.html
{% extends "base.html" %}

{% block title %} {{block.super}} | es_for {% endblock title %}

{% block content %}
    Cicla una sequenza usando <b>forloop.counter</b>
    <br/>
    {%for x in list2%}
        <i> {{forloop.counter}}</i> :{{x}} <br>
    {% endfor %}
    <br/>
    Cicla una sequenza usando <b>forloop.counter0</b>
    <br/>
    {%for x in list2%}
        <i> {{forloop.counter0}}</i> :{{x}} <br>
    {% endfor %}
    <br/>
<!---->
    Stampa il primo elemento della sequenza unsando <b> forloop.first </b>
    <br/>
    {%for x in list2%}
        {% if forloop.first %}
        <i> il primo elemento</i> - {{ x }}
        {% endif %}
    {% endfor %}
    <br/>
    Stampa l'ultimo elemento della sequenza unsando <b> forloop.last </b>
    <br/>
    {%for x in list2%}
        {% if forloop.last %}
        <i> l'ultimo elemento</i> - {{x}}
        {% endif %}
    {% endfor %}
    <br/>
<!---->
    Stampa il numero degli elementi non ancora ciclati <b> forloop.revcounter </b>
    <br/>
    {%for x in list2%}
        <i> numero elementi da dover ancora ciclare </i> - {{ forloop.revcounter }} <br/>
        <i> elemento </i> - {{x}} <br/>
    {% endfor %}
    <br/>
    Stampa il numero degli elementi non ancora ciclati <b> forloop.revcounter0 </b>
    <br/>
    {%for x in list2%}
        <i> numero elementi da dover ancora ciclare </i> - {{ forloop.revcounter0 }} <br/>
        <i> elemento </i> - {{x}} <br/>
    {% endfor %}
    <br/>
<!---->
    Stampa la sequenza al contrario usando  <b> reversed </b> attributo del tag <b> for </b>:
    <br/>
    {%for x in list2 reversed%}
        <i> elemento </i> - {{x}} <br/>
    {% endfor %}
{% endblock content %}

seconda_app/templates/es_if.html
{% extends "base.html" %}

{% block title %} {{block.super}} | es_if {% endblock title %}

{% block content %}
    <b>var1= {{ var1 }}</b> <br/>
    <b>var2= {{ var2 }}</b> <br/>
    <b>var3= {{ var3 }}</b> <br/>
    {% if var1 < var2%}
        <p><i> var1 è minore di var2 </i></p>
    {% endif %}
    {% if var1 > var2%}
        <p><i> var1 è maggiore di var2 </i></p>
    {% endif %}
    {% if var1 <= var2%}
        <p><i> var1 è minore o uguale di var2 </i></p>
    {% endif %}
    {% if var1 >= var2%}
        <p><i> var1 è maggiore o uguale di var2 </i></p>
    {% endif %}
    {% if var1 == var2%}
        <p><i> var1 è uguale a var2 </i></p>
    {% endif %}
    {% if var1 != var2%}
        <p><i> var1 non è uguale a var2 </i></p>
    {% endif %}
    {% if var1 < var2 and var1 < var3 %}
        <p><i> var1 è minore di var2 e var1 è minore di var3</i></p>
    {% endif %}
    {% if var1 < var2 or var3 < var2 %}
        <p><i> var1 è minore di var2 o var3 è minore di var2</i></p>
    {% endif %}
    {% if not var1 > var2%}
        <p><i> var1 non è maggiore di var2 </i></p>
    {% endif %}
{% endblock content %}

seconda_app/templates/if_else_elif.html
{% extends "base.html" %}

{% block title %} {{block.super}} | if_else_elif {% endblock title %}

{% block content %}
    <b>var1= {{ var1 }}</b> <br/>
    <b>var2= {{ var2 }}</b> <br/>
    <b>var3= {{ var3 }}</b> <br/>
    {% if var1 < var2 %}
        <p><i> var1 è minore di var2 </i></p>
    {% elif var1 > var2 %}
        <p><i> var1 è maggiore di var2 </i></p>
    {% else %}
        <p><i> var1 è uguale a var2 </i></p>
    {% endif %}
    {% if var1 > var2 %}
        <p><i> var1 è maggiore di var2 </i></p>
    {% elif var1 < var2 %}
        <p><i> var1 è maggiore di var2 </i></p>
    {% else %}
        <p><i> var1 è uguale a var2 </i></p>
    {% endif %}
    {% if var1 <= var2%}
        <p><i> var1 è minore o uguale di var2 </i></p>
    {% elif var1 > var2 %}
        <p><i> var1 è maggiore di var2 </i></p>
    {% endif %}
    {% if var1 >= var2%}
        <p><i> var1 è maggiore o uguale di var2 </i></p>
    {% elif var1 < var2 %}
        <p><i> var1 è minore di var2 </i></p>
    {% endif %}
    {% if var1 == var2%}
        <p><i> var1 è uguale a var2 </i></p>
    {% elif var1 != var2 %}
        <p><i> var1 non è uguale a var2 </i></p>
    {% endif %}
    {% if var1 < var2 and var1 < var3 %}
        <p><i> var1 è minore di var2 e var1 è minore di var3</i></p>
    {% elif var1 > var2 and var1 > var3 %}
        <p><i> var1 è maggiore di var2 e var1 è maggiore di var3</i></p>
    {% endif %}
    {% if not var1 > var2 %}
        <p><i> var1 non è maggiore di var2 </i></p>
    {% elif not var1 < var2 %}
        <p><i> var1 non è minore di var2 </i></p>
    {% else %}
        <p><i> var1 è uguale a var2 </i></p>
    {% endif %}
{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <style>
        *{
            font-family: 'Montserrat', sans-serif;
        }
    </style>

    <title>{% block title %} {% endblock title %}</title>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #9BDAD5;">
        <a class="navbar-brand;" style="color: white; font-weight: 800; font-size: 20px;" href="/">Primo progetto</a>
        <div class="dropdown">
            <a class="nav-link dropdown-toggle" href="{% url 'prima_app:index'%}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: white; font-family: 'Montserrat', sans-serif;" >
                Prima app
              </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="{% url 'prima_app:homepage'%}">Home page</a>
              <a class="dropdown-item" href="{% url 'prima_app:welcome'%}">Welcome</a>
              <a class="dropdown-item" href="{% url 'prima_app:lista'%}">Lista</a>
              <a class="dropdown-item" href="{% url 'prima_app:chi_siamo'%}">Chi siamo</a>
              <a class="dropdown-item" href="{% url 'prima_app:variabili'%}">Variabili</a>
            </div>
        </div>

        <div class="dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: white; font-family: 'Montserrat', sans-serif;">
                Seconda app
              </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="{% url 'seconda_app:es_for'%}">Es for</a>
              <a class="dropdown-item" href="{% url 'seconda_app:es_if'%}">Es if</a>
              <a class="dropdown-item" href="{% url 'seconda_app:if_else_elif'%}">If else elif</a>
            </div>
        </div>

        <div class="dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: white; font-family: 'Montserrat', sans-serif;">
                News
              </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="{% url 'news:Lista_giornalisti'%}">Giornalisti</a>
              <a class="dropdown-item" href="{% url 'news:Lista_articoli'%}">Articoli</a>
            </div>
        </div>

        <div class="dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: white; font-family: 'Montserrat', sans-serif;">
              Prova_pratica_1
            </a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{% url 'Prova_pratica_1:view_b'%}">View b</a>
            <a class="dropdown-item" href="{% url 'Prova_pratica_1:view_c'%}">Viwe c</a>
          </div>
        </div>

        <div class="dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: white; font-family: 'Montserrat', sans-serif;">
              API
            </a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{% url 'Prova_pratica_1:view_e'%}">View e</a>
          </div>
        </div>
          
        

      </div>
    </nav>
    
    <div class="container my-4">
        {%block content%} {%endblock content%}

    </div>
</body>
</html>